# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa0842054deae67869f47844e9c19d41864c0853a088cc770b36bd56c2feb11e2d63ead3d928e9cfb3f01f47c495402ee618a5d4aa13eeb60ff5fec5ed92ff5f

test:
  secret_key_base: def3b5c19324d70d03fd1d8a1e2c445816ffd0cabf95600c1a3a30fd8f8df1f31069d0a137dd673243a7d3c4041c2247e46adf4c898220bb4d29ce42b162dd8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
