source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'mysql2', '>= 0.3.13', '< 0.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'kaminari'

gem 'simple_form'
gem 'nested_form'

gem 'devise'
gem 'declarative_authorization'

gem "therubyracer"
gem "less-rails"
gem "twitter-bootstrap-rails"

gem 'mini_magick'
gem 'carrierwave'

gem 'ffaker'

gem 'friendly_id', '~> 5.1.0'
gem 'best_in_place'

group :development, :test do
  gem 'byebug'
  gem 'railroady'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

